service: mlb-streaker
frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  fixtures:
    handler: mlb/fixtures.index
    events:
      - http:
          path: /mlb/fixtures
          method: GET
  selections:
    handler: mlb/selections.index
    events:
      - http:
          path: /mlb/selections
          method: GET
